version: '3'

services:
  labyrinth-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    restart: unless-stopped
    volumes:
      - ./:/app 