name: Build and Deploy

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/labyrinth-server:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/labyrinth-server:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/labyrinth-server:buildcache,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # Stop and remove any existing container
            docker stop labyrinth-server || true
            docker rm labyrinth-server || true
            
            # Pull the latest image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/labyrinth-server:latest
            
            # Run the container with both TCP and UDP mapped
            docker run -d \
              --name labyrinth-server \
              -p 5000:5000/tcp \
              -p 5000:5000/udp \
              --restart unless-stopped \
              ${{ secrets.DOCKERHUB_USERNAME }}/labyrinth-server:latest 